### ISSUE TITLE
Etc2 RGB8A1 format support?

### ISSUE THREAD

**Issue by ryancheung** [darksylinc/betsy#2]
I currently use google's etc2comp to compress etc2 RGB8A1 for mobile platforms. But it seems slow.
Is it possible to do that in GPU?

Codec ref: https://github.com/google/etc2comp/blob/master/EtcLib/EtcCodec/EtcBlock4x4Encoding_RGB8A1.h

**Comment by darksylinc** [comment]
I just added ETC2 support (RGB8 and RGBA8).
Betsy now supports:

 - ETC1 RGB8
 - ETC2 RGB8
 - ETC2 RGBA8

There is no support for RGB8A1 (alpha punch-through) though, and I'm afraid it is not planned.

Does this answer your question?

**Comment by ryancheung** [comment]
Thanks for the answer. But I believe rgb8a1 format is also important. It just use 1bit alpha and can produce more high quality texture.
