### ISSUE TITLE
Create binary releases for Betsy on major platforms.

### ISSUE THREAD

**Issue by fire** [darksylinc/betsy#3]
Create binary releases for Win10 and Linux. Mac is less used, so it's up to you.

Why? Because you mentioned Betsy had hard to compile deps like sdl for Windows. Linux is also not that common.

**Comment by darksylinc** [comment]
[Done](https://github.com/darksylinc/betsy/releases/tag/v1.0-beta)

Mac cannot be supported, because there is no OpenGL compute shader support in that platform.
