### ISSUE TITLE
Can't output a texture on windows 10

### ISSUE THREAD

**Issue by fire** [darksylinc/betsy#4]
```
.\betsy.exe .\50496585556_94b95fd9d4_o.jpg --codec=etc2_rgba "put.ktx"
Initializing API
GL Context creation suceeded.
Could not save to 'α♦p♣ú☻' Check write access and whether the disk is full
Shutting down
```

Can't output a texture on windows 10.

![50496585556_94b95fd9d4_o](https://user-images.githubusercontent.com/32321/96372912-21482780-111e-11eb-9c42-8139f2a56206.jpg)

https://www.flickr.com/photos/studebakerbirds/50496585556/in/explore-2020-10-17/

**Comment by darksylinc** [comment]
Interesting. There seems to be some memory corruption going on.

It seems the cause is that the picture's resolution is not a multiple of 4 (a known limitation of ETC2).

Betsy should internally upscale the image from 3802x2517 to 3804x2520

**Comment by darksylinc** [comment]
It seems it was two bugs in one:

1. Resolutions with non-multiple of 4 were broken.
1. On Windows the command line parser was broken. 

I'll be uploading a new binary release today

**Comment by darksylinc** [comment]
[Done](https://github.com/darksylinc/betsy/releases/tag/v1.1-beta)

Thanks for the report!

**Comment by fire** [comment]
This is not exactly the test case but it works on Fedora 33.

![image](https://user-images.githubusercontent.com/32321/97120625-9c3caf80-16d5-11eb-8534-54dc68dad6df.png)

PS. Do you know how to open KTX files for BC5 and BC6?

**Comment by darksylinc** [comment]
Unfortunately I don't. Most viewers out there (all the ones I tried) are horribly working and only support a small subset of formats.

I gave up on that and debugged the output on RenderDoc (add '--renderdoc' to command line)
